### PR TITLE
Fix #1040: Build fails due to missing Alex data constructors 

### LINKED ISSUE #1040: Build fails due to missing Alex data constructors
```
    /home/siddhu/code/yi/yi-misc-modes/src/Yi/Lexer/common.hsinc:75:17-27: error:
        Not in scope: data constructor ‘AlexAccPred’
    
    /home/siddhu/code/yi/yi-misc-modes/src/Yi/Lexer/common.hsinc:80:17-31: error:
        Not in scope: data constructor ‘AlexAccSkipPred’
        Perhaps you meant ‘AlexAccSkip’ (line 207)
```

Just did git clone and stack build.

```bash
$ stack exec -- alex --version
Alex version 3.2.1, (c) 2003 Chris Dornan and Simon Marlow
$ stack exec -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ cat stack.yaml | grep resolver
resolver: lts-8.18
```

### PR DESCRIPTION
**Pull request by stites**

### CODE REVIEW

**Comment by noughtmare** [comment]
@siddhanathan Can you confirm that this also works for you?

**Comment by siddhanathan** [comment]
Wouldn't this cause the build to fail with older versions of Alex that don't have these constructors?

**Comment by noughtmare** [comment]
This fails if alex **has** the constructors. Since the `NO_ALEX_CONTEXT` flag causes the code to **not** be included.

**Comment by siddhanathan** [comment]
I suspect it might break existing installations that don't have this issue.

@ethercrow would you be able to test this on your setup? I remember you didn't have this issue.

**Comment by noughtmare** [comment]
It still compiles for me (I also didn't have the issue), but that can be because even if the code is not included, it will still compile, it will just throw an error about how there are non-exhaustive patterns. I've tried to build with `-Wall` and `--pedantic`, but that didn't give any errors (which made me wonder if it had any effect at all).

**Pull request merged**
