### PR TITLE
Add supporting of pasting text on Ex

### PR DESCRIPTION
**Pull request by aiya000**
I consumed a TODO on ExMap.hs :smile:

### CODE REVIEW

**Comment by ethercrow** [comment]
Thank you!

Could you also add a vimtest for this binding here https://github.com/yi-editor/yi/tree/master/yi-keymap-vim/tests/vimtests/ex ?

**Comment by aiya000** [comment]
gmmmm...  
Sorry, please wait :worried:

**Comment by aiya000** [comment]
hi :smile:  
I think Yi.Keymap.Vim.ExMap.putRegisterBinding test should not be add https://github.com/yi-editor/yi/tree/master/yi-keymap-vim/tests/vimtests/ex :thinking:,  
because putRegisterBinding is impure.  
It uses internal YiM...

How about that ? :joy:

**Comment by ethercrow** [comment]
It should be pure because it only touches the internal state and buffers. The only reason it's impure not is `liftBase getChar`.

**Comment by ethercrow** [comment]
To get rid of `getChar`, your binding should accept `<C-r>` plus variable register name instead of just `C-r`.

**Comment by aiya000** [comment]
Sorry ...
I tried it, but I couldn't exclude impure :sob:

I think that EventString is sent to [editAction](https://github.com/yi-editor/yi/blob/master/yi-keymap-vim/src/Yi/Keymap/Vim/ExMap.hs#L167) from [genericHandleEvent](https://github.com/yi-editor/yi/blob/master/yi-keymap-vim/src/Yi/Keymap/Vim.hs#L120).
But I think eventToString allow one stroke key only...

**Comment by aiya000** [comment]
Excluding EditorM () was completed :joy_cat:  
https://gist.github.com/fc4e3c6599b9b9dffaae1110db5bff70#file-ExMap-hs

**Comment by aiya000** [comment]
I completed this problem !! :smiley:

**Comment by ethercrow** [comment]
Great progress! Now it would be excellent if tests somehow checked that the correct word is pasted into Ex command line. I'm thinking that a test case like this should be fine:

input:
```
sort 3
sort 2
sort 1
```

Actions: yank the word `sort` into a register, use it with your new binding to execute `:%sort` on a file

Desired output:
```
sort 1
sort 2
sort 3
```

**Comment by aiya000** [comment]
I finished it :smile:

And I found a behavior.  
The Ex commands weren't executed by genericHandleEvent If VimState's vsOngoingInsertEvents is empty string.

This is a bug ?

**Comment by ethercrow** [comment]
Great job, thank you!

**Comment by aiya000** [comment]
:+1:

**Pull request merged**
