### PR TITLE
Count does work now for text objects in visual mode

### PR DESCRIPTION
**Pull request by Hi-Angel**
https://github.com/yi-editor/yi/issues/887#issuecomment-237249541

### CODE REVIEW

**Comment by ethercrow** [comment]
Could you add some tests too?

**Comment by Hi-Angel** [comment]
Yes, of course! I think… I never worked with `stack test`, so it wouldn't be quick :Ь but I'll do.

**Comment by noughtmare** [comment]
**Disclaimer:** I have never written vim tests.

[This](https://github.com/yi-editor/yi/commit/610989e3e9108b588af62ec9d61e9d5ded7d293b#diff-d0e1298e8fc9eab87a23715f1e12a1cb) is an example of a test. I think you just put a file `nameofcommand.test` in the ` src/tests/vimtests/visual` folder. The tuples right underneath the `-- Input` and `-- Output` lines denote the position of the cursor.

**Comment by Hi-Angel** [comment]
Well, looking at the test **ethercrow** have written in a commit, I can guess how does it work. However, I must say, running `stack test` fails with

	Progress: 11/12test-suite: src/tests/vimtests/digraphs/eacute.test: hGetContents: invalid argument (invalid byte sequence)

I'll probably try master branch, but to me it doesn't seem like the visual objects changes have to do anything with it.

**Comment by Hi-Angel** [comment]
Yeah, the same. I must say, if I follow the test manually, the result if perfectly fine.

**Comment by Hi-Angel** [comment]
Wow, so my commit automagically get into the pull request? That's cool, probably, but confusing…

**Comment by Hi-Angel** [comment]
Hmm… I must say, yi visual selection behaves very differently. E.g. on `test.cpp` where I tested, the text space was counted as a text object. But in a `.test` file, for whatever reason, it *includes* space into previous text object.

**Comment by noughtmare** [comment]
You can always test how it works in vim to find out how it should work.

**Comment by Hi-Angel** [comment]
@noughtmare  well, in vim it counts a space as a text object. And so does `evil` in Emacs.

**Comment by Hi-Angel** [comment]
Okay, do not merge, I'll try then to find why does Yi does behaves differently.

**Comment by Hi-Angel** [comment]
Ah, I see what's the problem — for some reason `viw` and `vaw` producing the same result. Ok, I'll dig a bit later why is this, gtg now.

**Comment by noughtmare** [comment]
Maybe you're using an older version which doesn't have the textobjects in visual mode, that way `viw` and `vaw` would both be equal to `vw`. Maybe that happened when you switched to the master branch?

**Comment by noughtmare** [comment]
I have changed the test to:
```
-- Input
(1,2)
123 456 789
-- Output
(1,1)
456 789
-- Events
v2iwx
```
(this is the behaviour I see in vim)
And it works correctly with your code.

**Comment by Hi-Angel** [comment]
Thank you, probably, you're right. I can't check it now, because I'm from another PC, but looks like it is.

So… Yay, it's ready to be merged!

There's one thing though, which I don't understand: `stack test` triggers an error for me:

	test-suite: src/tests/vimtests/digraphs/eacute.test: hGetContents: invalid argument (invalid byte sequence)

However, if I manually going trought that test in Yi, I see it ought to complete just fine. What could that be?

**Comment by ethercrow** [comment]
```
test-suite: src/tests/vimtests/digraphs/eacute.test: hGetContents: invalid argument (invalid byte sequence)
```
Maybe your locale is not UTF8?

**Comment by Hi-Angel** [comment]
Hm, you're right. I set `LANG=C` in my `~/.bashrc` in order to always get messages in English, and not my language *(for two reasons: they easier to google, and Konsole have rendering problems with unicode letters)*. I thought it would have the same effect as *en_EN.utf8*, or whatever it is called, but, seems, it's not.

Anyway, I just run the test like `LANG=ru_RU.utf8 stack test`, and they passed, so, I guess, we can close the bug with text objects in visual mode, right? ☺

**Comment by ethercrow** [comment]
Конечно.

**Comment by noughtmare** [comment]
The `v2iwx` test still failed. I think it needs to be changed like I said [here](https://github.com/yi-editor/yi/pull/890#issuecomment-237880377).

**Comment by Hi-Angel** [comment]
@noughtmare but I removed that test, and added the v3iwx

**Comment by noughtmare** [comment]
Hmm... that commit doesn't show up in this thread (in my browser). Strange.

**Pull request merged**
