### PR TITLE
Made reversePattern work without Plated instance

### LINKED ISSUE #836: Figure out what to do about `Plated` typeclass
(This is about `yi-language`, given that it should eventually be in this repo)

We've duplicated the `Plated` typeclass because Microlens does not provide it. There is a very good reason that it doesn't; it can maintain compatibility with Lens for most uses because *lens is based on type synonyms*. However, it doesn't provide type classes like `Plated` for the same reason that we should not use them: It makes the instances useless when used with the real `lens` library, and any functions we define polymorphically against `Plated` are only useful within Yi.

We should either:
1) Rewrite the code in a way that doesn't require us to define the `Plated` typeclass and an instance of it. Since nothing we are using externally can possibly be requiring an instance of this (because our `Plated` typeclass is not immediately compatible with the real one) this should definitely be possible.
2) Switch back to lens (although I'm clearly the only one that feels like this should be an option) and deal with having longer compilation times. I personally feel like the longer compilation times are solved by stack, not by microlens.

My stance is that I'm not necessarily against microlens but I am against adding technical debt that would not be there if we were using lens.

cc @noughtmare

### PR DESCRIPTION
**Pull request by noughtmare**
Fixes #836.

### CODE REVIEW

**Comment by jhance** [comment]
Do we have any test coverage for the reverse regex? If not its fine as long as you tested inside of Yi. it looks good to me.

**Comment by noughtmare** [comment]
Due to my inexperience with git I merged instead of rebasing (while you explicitly stated otherwise), is that a problem? If so, how can I fix it?

**Comment by jhance** [comment]
Its not a problem, rebasing is my personal preference simply because it makes it easier to review, but this is a small change and I understand well what you've done.

The only thing I'm maybe concerned about is that I'd prefer we use `Tasty` as the test engine rather than hspec (can tasty call into hspec?)

I know we use hspec within yi-language but most of our tests are within yi-core and use tasty.

**Comment by jhance** [comment]
Converted the merge to a rebase, and merged the last two commits for cleanliness. This is merged now.

**Pull request closed without merging**
