### PR TITLE
Derived some things directly in Yi.Tag

### LINKED ISSUE #875: Derive Binary directly in Yi.Tag
I don't know what the disadvantages are, but it would make the code simpler.

An example:
change
```Haskell
newtype Tag = Tag { _unTag :: T.Text } deriving (Show, Eq, Ord)
instance Binary Tag where
  ...
```
to
```Haskell
{-# GeneralizedNewtypeDeriving #-}
newtype Tag = Tag { _unTag :: T.Text } deriving (Show, Eq, Ord, Binary)
```

### PR DESCRIPTION
**Pull request by noughtmare**
Also removed Typable instance.

Fixes #875

### CODE REVIEW

**Comment by jhance** [comment]
Why did you remove the `Typeable` instance?

**Comment by noughtmare** [comment]
It's unnecessary since GHC 7.10

**Comment by jhance** [comment]
oh, cool

I'm actually wondering if we even need a `Binary` instance, what happens if you remove it?

**Comment by noughtmare** [comment]
```
src/Yi/Tag.hs:152:10-24:
    No instance for (Binary Tag)
      arising from a use of ‘binary-0.7.5.0:Data.Binary.Class.$gdmput’
    In the expression: binary-0.7.5.0:Data.Binary.Class.$gdmput
    In an equation for ‘put’:
        put = binary-0.7.5.0:Data.Binary.Class.$gdmput
    In the instance declaration for ‘Binary TagTable’
```

**Comment by noughtmare** [comment]
I removed all the binary instances in Yi.Tag and got this:
```
src/Yi/Tag.hs:69:10-24:
    No instance for (binary-0.7.5.0:Data.Binary.Class.Binary Tags)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘YiVariable Tags’
```

**Comment by jhance** [comment]
Oh sorry, you're right. I misread, the config variable is the tag list

Derp

**Comment by jhance** [comment]
The travis build seems to be hung...

**Comment by noughtmare** [comment]
It's still building my previous commit (which I overwrote with `git push -f`)

**Pull request merged**
