### PR TITLE
Add static example configs for vim and emacs

### PR DESCRIPTION
**Pull request by ethercrow**

### CODE REVIEW

**Comment by jhance** [comment]
Should the static configs thread in `do_args` to the config?

**Comment by noughtmare** [comment]
The modes (e.g. `Yi.Config.Default.HaskellMode` with `configureHaskellMode`) need to be configured too. And the `hiding (super)` is unnecessary.

**Comment by ethercrow** [comment]
> Should the static configs thread in do_args to the config?

I would leave it as is until the first complaint. Not all options handled by `do_args` make sense for a static build so it would be confusing to silently ignore them or quite boilerplatey to explicitly filter them out in example configs.

**Comment by jhance** [comment]
I have a branch that might help with that, I should finally get around to publishing that.

I do agree that dyre needs to be removed from the core option parsing before we can use them in a static build though

**Comment by noughtmare** [comment]
Also, GPL-3 is not compatible with Yi's GPL-2.

**Comment by jhance** [comment]
We should just standardize everything on `3` then?

**Comment by noughtmare** [comment]
Well, think we would have to contact all authors and get permission, because some of it is their copyright.

**Comment by jhance** [comment]
Yeah, true.

It seems like by default GPLv2 in a cabal package refers to v2 only, so we do indeed need to release everything under 2.

We should consider forcing contributors for forfeit copyright or something, but its too late now.

**Comment by ethercrow** [comment]
Good catch with the license.

> We should consider forcing contributors for forfeit copyright or something (like most large projects), but its too late now.

The tradition is to rewrite everything from scratch. Agda and Idris probably don't have a text editor yet.

**Comment by jhance** [comment]
Its okay, we just have to wait until 8.8 and we can rewrite the editor with dependent types!

**Comment by jhance** [comment]
nitpick: We are using `package.yaml` now in most of our projects (which I personally prefer, because it does have some nice things like sharing dependencies between the main library and testsuite)

**Comment by noughtmare** [comment]
I think the .cabal files should still be included for people who don't use stack/hpack.

**Pull request merged**
