### PR TITLE
Added :read command for the vim keymap

### LINKED ISSUE #720: Vim emulation : read command
In ViM, you can insert the output of a file with `:r myfile.txt`.
It can also be used to insert the output of external command, for example : `:r !ls`.

In my version, I have `Not an editor command: r`.

yi version : 0.11.1
GHC version : 7.8.3
OS : Debian unstable

### PR DESCRIPTION
**Pull request by noughtmare**
Fixes #720.

### CODE REVIEW

**Comment by noughtmare** [comment]
:read now inserts the text before the current line. Vim's default behaviour is to insert the text after the current line. I'm not sure how to implement this correctly.

**Comment by ethercrow** [comment]
You could look at what pasting does when the register style is LineWise, but actually Vim always annoys me with its insert-after behavior, so don't worry about it.

I'll review and merge as soon as I have some free time. Thank you for working on yi!

**Comment by noughtmare** [comment]
To make this behave more like vim: 
- Add `import Yi.Buffer.Misc (lineDown)`
- Change `withCurrentBuffer $ insertRopeWithStyleB s LineWise` to `withCurrentBuffer $ lineDown >> insertRopeWithStyleB s LineWise`

**Comment by noughtmare** [comment]
The tests fail because `vty-5.7` (2016-9-26) has dropped `GHC-7.8` support.

**Pull request merged**
