### PR TITLE
Added unicode support to Haskell lexer

### LINKED ISSUE #723: Non—ASCII glyphs being marked with red background in string literals
When editing Haskell files non—ASCII glyphs are highlighted as errors in string literals (see screenshot)

### PR DESCRIPTION
**Pull request by noughtmare**
I generated these using:
```
$ wget http://www.unicode.org/Public/UNIDATA/UnicodeData.txt
$ grep UnicodeData.txt -e ";S[^;]\?;" | grep -wo "^[0-9A-F]\+" > symbols.txt
$ grep UnicodeData.txt -e ";Ll;" | grep -wo "^[0-9A-F]\+" > lower.txt
$ grep UnicodeData.txt -e ";L[ut];" | grep -wo "^[0-9A-F]\+" > upper.txt
```
and then wrote my own haskell program to clean the output files:
```Haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Data.Monoid
import Data.Attoparsec.ByteString.Char8
import qualified Data.ByteString.Char8 as B
import System.Environment
import Numeric (showHex)

main :: IO ()
main = do
  args <- getArgs
  case args of
    [infile, outfile] -> do
      ll <- B.lines <$> B.readFile infile
      B.writeFile outfile . surroundWith "[" "]" . simplify $ map (fromRight . parseOnly hexadecimal) ll
    _ -> error "Usage: unicoderanges infile outfile"

fromRight :: Either a b -> b
fromRight (Right a) = a

simplify :: [Int] -> B.ByteString
simplify [] = mempty
simplify all@(a:b:c:_) 
  | succ a == b && succ b == c = let ((start,end),rest) = takeSuccs all 
      in B.pack ('\\' : 'x' : showHex start ('-' : '\\' : 'x' : (showHex end ""))) <> simplify rest
  | otherwise = B.pack ('\\' : 'x' : showHex a "") <> simplify (tail all)
simplify (x:xs) = B.pack ('\\' : 'x' : showHex x "") <> simplify xs

takeSuccs :: [Int] -> ((Int,Int),[Int])
takeSuccs (x:xs) = takeSuccs' x x xs
  where
    takeSuccs' :: Int -> Int -> [Int] -> ((Int,Int), [Int])
    takeSuccs' start end [] = ((start,end),[])
    takeSuccs' start end rest@(x:xs) | succ end == x = takeSuccs' start x xs
                                     | otherwise = ((start,end),rest)

surroundWith :: B.ByteString -> B.ByteString -> B.ByteString -> B.ByteString
surroundWith start end string = start <> string <> end
```
Finally, I added `_` to `$lower` (should `_` be escaped?).

Should fix #723

### CODE REVIEW

**Comment by jhance** [comment]
Somewhat concerned about the memory usage of the compiled regexes here...

**Comment by noughtmare** [comment]
The effect on memory usage is unnoticeable for me.

**Comment by jhance** [comment]
Okay cool (the only reason I was concerned is because a python library has an issue with a big unicode regex lol)

**Comment by Fuuzetsu** [comment]
A better way for the future would be to try and get these from GHC.

**Pull request merged**
