### PR TITLE
Add Flags back in

### PR DESCRIPTION
**Pull request by noughtmare**
I might have added outdated flags (like testing).

### CODE REVIEW

**Comment by noughtmare** [comment]
PS: hint is now disabled by default because it contains critical errors.

**Comment by ethercrow** [comment]
Why are these flags in yi-core instead of yi package? The latter is the one that has the binary and is the one that a user will try to install first.

Also let's remove -ftesting.

**Comment by noughtmare** [comment]
The flags are in yi-core, because that's where they have effect. Is there a way to pass flags to dependencies? 

Also I don't think a new user would want to set flags.

**Comment by jhance** [comment]
It's not possible based on quick Google (could be outdated)

**Comment by jhance** [comment]
I think we can split hint to a separate package?

**Pull request merged**
