### PR TITLE
Change indentation to solve issue #725

### PR DESCRIPTION
**Pull request by niilohlin**

### CODE REVIEW

**Comment by siddhanathan** [comment]
The do block on L177 seems redundant. It would be more readable if it used a where clause instead.

```
else go (abs count * w)
     where go 0 = ...
```

**Comment by niilohlin** [comment]
You're right, I will refactor.

**Comment by ethercrow** [comment]
Couple of tests for this issue:

```
% cat src/tests/vimtests/visual/indent_12.test 
-- Input
(1,1)

def main():
foo()
bar()

baz()
quux()

-- Output
(3,5)

def main():
    foo()
    bar()

    baz()
    quux()

-- Events
jj<C-v>}}>

% cat src/tests/vimtests/visual/indent_13.test
-- Input
(1,1)

def main():
        foo()
        bar()

        baz()
        quux()

-- Output
(3,5)

def main():
    foo()
    bar()

    baz()
    quux()

-- Events
jj<C-v>}}<lt>
```

**Comment by niilohlin** [comment]
Commit https://github.com/niilohlin/yi/commit/0047d3cbce6c31ad3c44d9dc36b409a3a7239eac passes the tests.

**Comment by siddhanathan** [comment]
Can you add the test files in this PR?

**Comment by niilohlin** [comment]
Wait, I'm sorry but cabal wasn't cooperating at first so I didn't actually run the tests. But the expected behaviour in the test is different from the behaviour in vim. The vim behavour is:

```
% cat src/tests/vimtests/visual/indent_12.test 
-- Input
(1,1)

def main():
foo()
bar()

baz()
quux()

-- Output
(3,1)

def main():
    foo()
    bar()

    baz()
    quux()

-- Events
jj<C-v>}}>

% cat src/tests/vimtests/visual/indent_13.test
-- Input
(1,1)

def main():
        foo()
        bar()

        baz()
        quux()

-- Output
(3,1)

def main():
    foo()
    bar()

    baz()
    quux()

-- Events
jj<C-v>}}<lt>
```

**Pull request merged**
