### PR TITLE
(#716) Migrate from regex-tdfa to text-icu

### PR DESCRIPTION
**Pull request by waynr**
@ethercrow

### CODE REVIEW

**Comment by ethercrow** [comment]
Hey @waynr, do you think you'll have time to work on this in foreseeable future?

**Comment by Fuuzetsu** [comment]
What needs doing still?

**Comment by jhance** [comment]
seems like the only usages of tdfa are in yi-language right now?

**Comment by siddhanathan** [comment]
@jhance Somewhat; I was supposed to remove tdfa from yi-language, but never got time to look into it. Since yi-language re-exports tdfa, traces of regex are still in there. Changes like https://github.com/siddhanathan/yi/commit/45e93794e12645af4ce3a7ddcda44b9a09bd7bca need to be done before yi-language can become independent of tdfa.

**Comment by waynr** [comment]
Hey y'all, apologies for lack of response when I was pinged before. Work has been really busy and I haven't even had time/energy for work-related free software/open source projects...

Also, I'm still pretty new to Haskell and couldn't quite figure out how to approach the exceptions I was seeing when attempting to remove tdfa from yi-language.

**Comment by jhance** [comment]
I don't think anyone has been very active to be fair (me especially -.-)

**Comment by neongreen** [comment]
Are you sure it's a valid change, given that regex-tdfa implements POSIX regexes and text-icu – PCRE regexes?

**Comment by ethercrow** [comment]
@neongreen I consider that an improvement.

**Comment by neongreen** [comment]
Possibly, but it could still have unintended consequences (e.g. if you have hardcoded regexes somewhere and they depend on POSIX semantics) and I decided to comment because, well, better safe than sorry. I prefer text-icu over regex-tdfa myself.

**Comment by codygman** [comment]
What was the original reason for moving to text-icu from regex-tdfa?

**Comment by ethercrow** [comment]
@codygman To get perl-like regexes. One of my annoyances with both emacs and vim is that you have to learn their regex flavors. There are other libraries that provide perl-like regexes in haskell, but we already depend on text-icu.

**Comment by noughtmare** [comment]
`text-icu`'s interface is very different from `regex-tfda` (and therefore hard to replace), i would recommend using `regex-pcre` for (fast) perl-like regexes. `text-icu` is used only in three modules, so it isn't to hard to replace.

**Comment by jhance** [comment]
Seems like `text-icu` has the advantage that it operates on `Text` rather than `ByteString`, though.

**Comment by jhance** [comment]
I think the primary problem is the reverse search with `text-icu`. I can't speak for `regex-pcre` (haven't looked closely) but `text-icu` represents its regex patterns as a pointer into a C object, so we can't reverse them in the same way we are doing now.

**Comment by noughtmare** [comment]
`regex-pcre` also has a pointer into a C object.

**Comment by noughtmare** [comment]
[regex-tdfa-text](https://hackage.haskell.org/package/regex-tdfa-text-1.0.0.3) allows `regex-tdfa` to work on text.

**Comment by jhance** [comment]
Yeah, but I don't think text usage is the reason for the switch its just a (pretty nice) icing.

The real trick is how to reverse a perl regex given that perl regexes are not necessarily reversible (backreferences...)

**Comment by noughtmare** [comment]
We could do something like `concatMap (reverse . match) . reverse . lines`, but we would lose the ability to do multiline matching.

**Comment by noughtmare** [comment]
Another option is to use `regex-tdfa` to reverse the regex and than pass that regex to `text-icu` by using `showPattern`.

**Comment by jhance** [comment]
We can. We can't reverse every pcre regex but we can reverse many is them. The basic method I would do for this is to use (atto)parsec to parse to an ast, reverse, and then reformat.

**Comment by Fuuzetsu** [comment]
I don't understand what you mean by reversing regex. Can you elaborate? Parsing regex ourselves sounds like a really wrong thing to do in any case I can think of that's reasonable.

**Comment by noughtmare** [comment]
Currently to search backwards in a file (with regexes) [we reverse the text and the regex](https://github.com/yi-editor/yi/blob/master/src/library/Yi/Buffer/Implementation.hs#L383) (e.g. `hello` becomes `olleh` and `a+bc*[de]|f` becomes `[de]c*ba+|f`). If we want to switch to PCRE we need to be able to reverse PCRE regexes (or search backwards in a file in another way).

This is how we currently reverse regexes (in the `split-packages` branch): https://github.com/yi-editor/yi/blob/split-packages/yi-language/src/Yi/Regex.hs#L99-L115

**Comment by jhance** [comment]
@Fuuzetsu I've googled *extensively* on the subject of reverse regex searches and can find no good way to find the last result without looping through all results (which is unacceptable). So we currently reverse the regex and reverse the input (which is easy to do with regex-tdfa, because it exposes an AST layer). The more powerful PCRE libraries do not (and not all PCRE expressions are reversable) so this is a problem.

(FYI, I sourcedived vim and I think they also do the reverse regex/reverse text trick but I'm not sure because the vim code is hideous)

**Comment by ethercrow** [comment]
Honestly, I don't remember even one occasion where yi would search anything but a literal string for me. I'd rather have sane regexes than fast backwards searching.

**Comment by jhance** [comment]
I don't disagree with that sentiment, only worried about an editor freeze if you accidently do `?a` in a large file.

**Comment by ethercrow** [comment]
In a sufficiently large file even a forward search would freeze the editor if the match is far ahead.

**Comment by jhance** [comment]
Hmm yeah, I agree with that.

We can just make rev-search slower in favor of getting PCRE regexes.

**Comment by siddhanathan** [comment]
When switching over to ICU, there are a few issues that could arise, such as ICU not exposing the offset and length of the matches (which we need in Buffer/Implementation.hs)

**Comment by noughtmare** [comment]
Closing this due to inactivity and because the text-icu dependency was dropped.

**Pull request closed without merging**
