### PR TITLE
Split yi-mode-haskell and yi-mode-javascript

### PR DESCRIPTION
**Pull request by noughtmare**
Is this the right way to do it?

### CODE REVIEW

**Comment by ethercrow** [comment]
It's going to be slightly more involved, because lexers live in https://github.com/yi-editor/yi-language. I guess you would need to move Haskell.x and LiterateHaskell.x from there to yi-mode-haskell.

Also, I was thinking about a package yi-stock-modes for simpler modes like json and make, so that we don't end up with 100 packages here. Haskell and JavaScript are prime candidates for extraction though.

**Comment by noughtmare** [comment]
I have moved them and opened yi-editor/yi-language#8.

**Comment by ethercrow** [comment]
I think I'll move yi-language into this repo as a subproject, because otherwise it's hard to keep them both in sync.

**Comment by jhance** [comment]
I'm modifying `yi-language` a bit right now so unless its a lot of work sync that before landing, I guess (otherwise I'll port over the changes by hand). I'm guessing we more or less just copied the repo in though, so it can be re-copied pretty easily.

**Pull request merged**
